### ISSUE TITLE
issue with loading weights for WRN-28-8

### ISSUE THREAD

**Issue by astha-chem** [titu1994/Wide-Residual-Networks#11]
This is a very useful repository - thank you for contributing.

I am trying to run the code for WRN-28-8 on Python 3 using Keras 2.1.1 and TensorFlow backend in a jupyter notebook. 

When I get to loading weights:

```
model.load_weights("weights/WRN-28-8 Weights.h5")
print("Model loaded.")
```

It throws an error: (full error message below my name) 

`ValueError: Layer #0 (named "conv2d_1" in the current model) was found to correspond to layer convolution2d_1 in the save file. However the new layer conv2d_1 expects 1 weights, but the saved weights have 2 elements.
`

Do you know what's going on here? To me this looks like a version issue, but your weights seem to be meant for Keras 2. What about the backend and python version? 

Thanks, 
Astha

```
Finished compiling
Allocating GPU memory
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-13-1a29b71a7c3c> in <module>()
      3 print("Allocating GPU memory")
      4 
----> 5 model.load_weights("weights/WRN-28-8 Weights.h5")
      6 print("Model loaded.")

~\Anaconda2\envs\tensorflow\lib\site-packages\keras\engine\topology.py in load_weights(self, filepath, by_name)
   2620             load_weights_from_hdf5_group_by_name(f, self.layers)
   2621         else:
-> 2622             load_weights_from_hdf5_group(f, self.layers)
   2623 
   2624         if hasattr(f, 'close'):

~\Anaconda2\envs\tensorflow\lib\site-packages\keras\engine\topology.py in load_weights_from_hdf5_group(f, layers)
   3138                              ' weights, but the saved weights have ' +
   3139                              str(len(weight_values)) +
-> 3140                              ' elements.')
   3141         weight_value_tuples += zip(symbolic_weights, weight_values)
   3142     K.batch_set_value(weight_value_tuples)

ValueError: Layer #0 (named "conv2d_1" in the current model) was found to correspond to layer convolution2d_1 in the save file. However the new layer conv2d_1 expects 1 weights, but the saved weights have 2 elements.
```

**Comment by titu1994** [comment]
The model has been updated but the weights have not. I suggest using newer models such as DenseNet or MobileNets.

**Comment by astha-chem** [comment]
I see, thanks. Well, I am trying to implement another paper which is based on this one, so I am trying to get a baseline level for this model on multiple datasets. I will go ahead and run it without initialization with model weights. In your experience, would that affect the accuracy too much? Would I need many more epochs to train?
