### ISSUE TITLE
Why subtract by 4 from the number of layers

### ISSUE THREAD

**Issue by ghost** [titu1994/Wide-Residual-Networks#18]
https://github.com/titu1994/Wide-Residual-Networks/blob/f71925796aa754ecfe50fa005da5e3773543d894/wide_residual_network.py#L118

I had another concern. In the original paper they mention that n is the number of convolutional layer, but I couldn't understand why did we subtract by 4 at the first hand. Are we treating n as the total number of layers including convolutional layers, i.e., are we counting batch norm and relu layer?

Thank you!!

**Comment by titu1994** [comment]
No it's not that we count BN and Activations as a complete layer, it's just that to stay consistent with the number of parameters of the paper and the number of conv blocks, that's the computation required. This is similar to ResNet v1/v2 depth and densenet depth.

**Comment by ghost** [comment]
According to the original densenet paper in https://arxiv.org/pdf/1608.06993.pdf, in table 1, I can tell that we have 1 conv layer that takes the direct input images, and we have additional 3 conv layers (in the transition layers), that will sum up to 4. However, I don't see transition layers in resnet_v1/v2. That's what create the confusion. Probably you are subtracting by 4 in order to counter the conv in the transition layers?

**Comment by titu1994** [comment]
Hmm. I haven't looked at the original paper in a long time, but I do remember without this trick having more parameters than the paper. I think I did it merely to keep parameter count consistent.

**Comment by ghost** [comment]
If I want to ignore the number of parameters due to the availability of memory resources, can I simply keep my working implementation fo resnet while multiplying each filter by k except for the first conv layer?

**Comment by titu1994** [comment]
Yes that would be ok.

**Comment by ghost** [comment]
Alright, thank you!!
