### ISSUE TITLE
wrn_28_8_tf_kernels_tf_dim_ordering_no_top.h5 requires object "flatten_2" when used without including top

### ISSUE THREAD

**Issue by citerana** [titu1994/Wide-Residual-Networks#5]
When I try to initialize a network using these cifar10 weights [wrn_28_8_tf_kernels_tf_dim_ordering_no_top.h5] on a model not including top, the load_weights method fails out with the error:

`File "h5py/h5o.pyx", line 190, in h5py.h5o.open (/home/ilan/minonda/conda-bld/h5py_1490028461908/work/h5py/h5o.c:3740)
KeyError: "Unable to open object (Object 'flatten_2' doesn't exist)"`

As the only flatten layer in the model is when you include top (i.e. including the following two layers) this seems like an error in the .h5 file.

`x = Flatten()(x)
x = Dense(nb_classes, activation='softmax')(x)`

**Comment by titu1994** [comment]
The model was updated today to match the paper more closely. It delivers better performance now, but I haven't trained the new model on Cifar 10 yet. 

I would rather suggest training on other models such as MobileNets, which has been trained on ImageNet with 1000 classes and is much more useful for fine-tuning. The downside is the smallest image size is 128x128, and largest is 224x224.  

I assume if you were using the WideResNer model, your image size is smaller ?

**Comment by titu1994** [comment]
Ive created an `old-model` branch, which will no longer be updated, and has the old model building code. If you absolutely wish to use the older model (which has weights, but performs worse than the newer model), then you can use that branch and download the model builder.
