### ISSUE TITLE
Maxpooling instead of conv(stride=2) in the WRN paper?

### ISSUE THREAD

**Issue by ViaFerrata** [titu1994/Wide-Residual-Networks#7]
First of all, thanks a lot for implementing the Wide-ResNet in Keras!
However, I've a question regarding the Max Pooling layer that is used to reduce the dimensionality between the ResNet blocks.

Is this really used in the WRN paper? 
Unfortunately I couldn't find any specific information in the paper, but according to their Torch implementation they use a stride of 2 at the beginning of each ResNet block type to reduce the dimensionality and not a Max Pooling layer.
(Torch: https://github.com/szagoruyko/wide-residual-networks/blob/master/models/wide-resnet.lua).
Such that it's similar to the original ResNet paper.

Or am I missing something (maybe it's also due to my poor Torch knowledge while reading their code)?

**Comment by titu1994** [comment]
The lua implementation you provided is correct. I implemented MaxPooling2D because it wasn't clear when the paper originally came out. 

Anyway, I have updated the model code now.
