### ISSUE TITLE
Implementation WRN-50-2

### ISSUE THREAD

**Issue by SankBad** [titu1994/Wide-Residual-Networks#8]
Have you tried implementing WRN-50-2 which is Wider Version of ResNet-50. 
It is mention in the latest version of this paper:
https://arxiv.org/pdf/1605.07146v4.pdf
This version is work with ImageNet Data, Can you give me some suggestion about how to do it in Keras?

**Comment by titu1994** [comment]
Haven't read the update in the WRN paper yet. What specific changes are their, if any ?

The WRN 50 cant be directly created I think. I haven't added support for lists as parameters, which is necessary for ResNet 50.

**Comment by titu1994** [comment]
Just read the changes. They use a non standard WRN for that. It would add a lot of complexity to the codebase for just one model. 

If I have time later on I may decide to do implement it but I suggest you go for other ResNet implementations and add the widening factor yourself.
